FROM public.ecr.aws/lambda/python:3.8

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY app.py app.py

# To correspond to AWS API Gateway "Stage Name"
ENV ROOT_PATH=/Prod 

CMD ["app.handler"]